General:
  Quit: true
  AlternateRows: false
  SmartCaseSensitive: true
  Incsearch: true
  WrapMode: false
  Style:
    Header:
      Bold: true
      Foreground: "#75c4f9"   # blue
    Alternate:
      Background: "#3a3d4b"   # alternate background
    SearchHighlight:
      Foreground: "#282935"   # background (for contrast)
      Background: "#f4f8a7"   # yellow
      Bold: true
    MarkLine:
      Background: "#3a3d4b"   # alternate background
    SectionLine:
      Bold: true
      Foreground: "#f4f8a7"   # yellow
    SectionHeaderBorder:
      Foreground: "#75c4f9"   # blue
    ColumnRainbow:
      - Foreground: "#f0f1f0" # white
      - Foreground: "#88f398" # green
      - Foreground: "#75c4f9" # blue
      - Foreground: "#f4f8a7" # yellow
      - Foreground: "#ed73bd" # magenta
      - Foreground: "#aceafb" # cyan
      - Foreground: "#ec675d" # red
    MultiColorHighlight:
      - Foreground: "#88f398" # green
      - Foreground: "#75c4f9" # blue
      - Foreground: "#f4f8a7" # yellow
      - Foreground: "#ed73bd" # magenta
      - Foreground: "#aceafb" # cyan
      - Foreground: "#ec675d" # red

Mode:
  psql:
    Header: 2
    AlternateRows: true
    ColumnMode: true
    ColumnDelimiter: "|"
  mysql:
    Header: 3
    AlternateRows: true
    ColumnMode: true
    ColumnDelimiter: "|"
  markdown:
    SectionDelimiter: "^#"
    Wrap: "word"
  csv:
    Header: 1
    AlternateRows: false
    ColumnMode: true
    LineNumMode: true
    ColumnDelimiter: ","
    ColumnRainbow: true
    Align: true
